# [build]
#   command = "npm run build"
#   publish = "client/build"

# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-url.com/api/:splat"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
